[tool.poetry]
name = "django-drf"
version = "0.1.0"
description = ""
authors = ["User <tooxa85@gmail.com>"]


[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
