# Generated by Django 5.2.3 on 2025-06-20 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="is_subscribe",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lms.course"
            ),
        ),
    ]
